import type { RoomDef, RoomKind } from "./types";

export const CATALOG: Record<RoomKind, RoomDef> = {
  lobby: {
    id: "lobby",
    name: "Lobby",
    blurb: "Ground-floor welcome hall. Tenants enter here.",
    cols: 6,
    rows: 1,
    cost: 4_200,
    stars: 1,
    capacity: 0,
    rent: 0,
    visitPay: 0,
    zone: "ground",
    group: "transit",
    icon: "columns",
  },
  stairs: {
    id: "stairs",
    name: "Stairs",
    blurb: "Connects this floor to the one above. Slow, but free of queues.",
    cols: 2,
    rows: 1,
    cost: 480,
    stars: 1,
    capacity: 0,
    rent: 0,
    visitPay: 0,
    zone: "any",
    group: "transit",
    icon: "stairs",
  },
  elevator: {
    id: "elevator",
    name: "Elevator",
    blurb: "Local cars. Click a built shaft to add more — they pass through each other.",
    cols: 2,
    rows: 1,
    cost: 2_400,
    stars: 1,
    capacity: 8,
    rent: 0,
    visitPay: 0,
    zone: "any",
    group: "transit",
    icon: "elevator",
  },
  express: {
    id: "express",
    name: "Express",
    blurb: "Faster, 16 riders, stops every 5 floors. Click the shaft to stack extra cars.",
    cols: 2,
    rows: 1,
    cost: 5_200,
    stars: 2,
    capacity: 16,
    rent: 0,
    visitPay: 0,
    zone: "any",
    group: "transit",
    icon: "express",
  },
  office: {
    id: "office",
    name: "Office",
    blurb: "Daytime tenants. Need elevator access and a place to eat.",
    cols: 6,
    rows: 1,
    cost: 2_400,
    stars: 1,
    capacity: 4,
    rent: 58,
    visitPay: 0,
    zone: "above",
    group: "work",
    icon: "briefcase",
  },
  fastfood: {
    id: "fastfood",
    name: "Cafe",
    blurb: "Lunch counter. Workers eat here or they walk out.",
    cols: 6,
    rows: 1,
    cost: 3_400,
    stars: 1,
    capacity: 10,
    rent: 0,
    visitPay: 11,
    zone: "any",
    group: "food",
    icon: "coffee",
  },
  hotel: {
    id: "hotel",
    name: "Double",
    blurb: "Two guests. Two-thirds the width of an office.",
    cols: 4,
    rows: 1,
    cost: 2_800,
    stars: 2,
    capacity: 2,
    rent: 92,
    visitPay: 0,
    zone: "above",
    group: "stay",
    icon: "bed",
  },
  single: {
    id: "single",
    name: "Single",
    blurb: "One guest. A third of an office bay — pack more rooms on a floor.",
    cols: 2,
    rows: 1,
    cost: 1_600,
    stars: 2,
    capacity: 1,
    rent: 48,
    visitPay: 0,
    zone: "above",
    group: "stay",
    icon: "single",
  },
  shop: {
    id: "shop",
    name: "Boutique",
    blurb: "Daytime retail. Pair with a restaurant to earn a three-star rating.",
    cols: 6,
    rows: 1,
    cost: 3_800,
    stars: 2,
    capacity: 8,
    rent: 0,
    visitPay: 16,
    zone: "any",
    group: "retail",
    icon: "bag",
  },
  parking: {
    id: "parking",
    name: "Parking",
    blurb: "Basement stalls. Slightly boosts office demand.",
    cols: 8,
    rows: 1,
    cost: 2_600,
    stars: 2,
    capacity: 6,
    rent: 9,
    visitPay: 0,
    zone: "below",
    group: "service",
    icon: "car",
  },
  condo: {
    id: "condo",
    name: "Condo",
    blurb: "Residents live here. They leave by day and return at night.",
    cols: 8,
    rows: 1,
    cost: 7_400,
    stars: 3,
    capacity: 3,
    rent: 148,
    visitPay: 0,
    zone: "above",
    group: "stay",
    icon: "home",
  },
  restaurant: {
    id: "restaurant",
    name: "Restaurant",
    blurb: "Evening dining. Unlocks at two stars — required, with a boutique, for three.",
    cols: 8,
    rows: 1,
    cost: 8_600,
    stars: 2,
    capacity: 14,
    rent: 0,
    visitPay: 24,
    zone: "any",
    group: "food",
    icon: "utensils",
  },
  medical: {
    id: "medical",
    name: "Clinic",
    blurb: "Calms angry tenants and quietly lifts your rating.",
    cols: 6,
    rows: 1,
    cost: 9_200,
    stars: 3,
    capacity: 4,
    rent: 0,
    visitPay: 18,
    zone: "any",
    group: "service",
    icon: "heart",
  },
  suite: {
    id: "suite",
    name: "Suite",
    blurb: "Three guests, same width as an office. Highest nightly rate.",
    cols: 6,
    rows: 1,
    cost: 9_400,
    stars: 4,
    capacity: 3,
    rent: 210,
    visitPay: 0,
    zone: "above",
    group: "stay",
    icon: "spark",
  },
  theater: {
    id: "theater",
    name: "Theater",
    blurb: "Two-story house. Evening crowds, big receipts, five-star bait.",
    cols: 12,
    rows: 2,
    cost: 18_500,
    stars: 4,
    capacity: 20,
    rent: 0,
    visitPay: 22,
    zone: "above",
    group: "retail",
    icon: "film",
  },
};

export const TOOL_ORDER: RoomKind[] = [
  "lobby",
  "stairs",
  "elevator",
  "express",
  "office",
  "fastfood",
  "single",
  "hotel",
  "shop",
  "parking",
  "condo",
  "restaurant",
  "medical",
  "suite",
  "theater",
];

export const GROUP_LABEL: Record<RoomDef["group"], string> = {
  transit: "Transit",
  work: "Work",
  stay: "Stay",
  food: "Food",
  retail: "Retail",
  service: "Service",
};
